# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=5, help_text='Item Price', verbose_name='Price'),
        ),
    ]
