# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0002_auto_20171203_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleinstance',
            name='net_coins',
            field=models.IntegerField(default=0, help_text='Coins won or lost', verbose_name='Net Coins'),
        ),
        migrations.AlterField(
            model_name='battleinstance',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Winner', to='nugget.Profile', verbose_name='Winner'),
        ),
    ]
