# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0003_auto_20171203_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battleinstance',
            options={'ordering': ['id', 'net_coins', 'nug_xp', 'opp_a', 'opp_b', 'stats_a', 'stats_b'], 'verbose_name': 'Battle', 'verbose_name_plural': 'Battles'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id', 'name', 'price', 'effect', 'effect2', 'item_status', 'item_features', 'item_features2'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id', 'usr', 'bday', 'coins', 'last_login_date'], 'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AddField(
            model_name='battleinstance',
            name='stats_a',
            field=models.CharField(default='', max_length=500, verbose_name='Stats Changes for Opponent A'),
        ),
        migrations.AddField(
            model_name='battleinstance',
            name='stats_b',
            field=models.CharField(default='', max_length=500, verbose_name='Stats Changes for Opponent B'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default='', help_text='Item Description', max_length=100, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='effect2',
            field=models.IntegerField(default=5, help_text='+/- Stat', verbose_name='+/- Stat'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_features2',
            field=models.CharField(blank=True, choices=[('he', 'Health'), ('hun', 'Hunger'), ('def', 'Defense'), ('f', 'Fatigue'), ('i', 'Intelligence'), ('happ', 'Happiness'), ('l', 'luck')], default='he', help_text='Type of Feature', max_length=100, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Last Login Date'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='battle_XP',
            field=models.IntegerField(default=0, help_text='Battle Experience Points', verbose_name='Battle XP'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='experience',
            field=models.IntegerField(default=0, help_text='Experience Points', verbose_name='XP'),
        ),
    ]
