# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0005_auto_20171205_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='msg_shop',
            field=models.CharField(default='', max_length=200, verbose_name='Message Field'),
        ),
    ]
