# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0007_forum_forumcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['id', 'user', 'subject', 'content', 'date']},
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.CharField(blank=True, default='None', help_text='Forum content', max_length=1000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='content',
            field=models.CharField(blank=True, default='None', help_text='Forum comment content', max_length=200, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
    ]
