# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0009_auto_20171211_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this forum post', primary_key=True, serialize=False, verbose_name='forum id')),
                ('topic', models.CharField(blank=True, default='General', help_text='Forum Topic', max_length=100, verbose_name='subject')),
                ('subject', models.CharField(blank=True, default='Subject', help_text='Forum Subject', max_length=100, verbose_name='subject')),
                ('content', models.CharField(blank=True, default='None', help_text='Forum Content', max_length=1000, verbose_name='content')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Post Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Profile', verbose_name='User in the chat')),
            ],
            options={
                'ordering': ['id', 'user', 'topic', 'subject', 'content', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ForumComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='None', help_text='Forum comment content', max_length=200, verbose_name='content')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Post Date')),
                ('originalPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Forum', verbose_name='link comment to a forum post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Profile', verbose_name='User in the chat')),
            ],
            options={
                'ordering': ['originalPost', 'user', 'content', 'date'],
            },
        ),
    ]
