# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nug_id', models.IntegerField(help_text='Nugget ID unique to User', max_length=8)),
                ('usr', models.CharField(help_text='Username', max_length=25)),
                ('email', models.EmailField(help_text='User Email', max_length=50)),
                ('pswd', models.CharField(help_text='User Password', max_length=50)),
                ('bday', models.DateField(auto_now=True)),
                ('coins', models.IntegerField(help_text='User Currency', max_length=10)),
            ],
            options={
                'ordering': ['nug_id', 'usr', 'email', 'pswd', 'bday', 'coins'],
            },
        ),
    ]
