# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(help_text='User Currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nug_id',
            field=models.IntegerField(help_text='Nugget ID unique to User'),
        ),
    ]
