# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0002_auto_20171022_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nugget name', max_length=25)),
                ('nug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.User')),
            ],
            options={
                'ordering': ['nug_id', 'name'],
            },
        ),
    ]
