# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0003_nugget'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuggetAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nug_color', models.CharField(help_text='Nugget color', max_length=50)),
                ('nug_size', models.DecimalField(decimal_places=2, max_digits=25)),
                ('mouth_size', models.DecimalField(decimal_places=2, max_digits=25)),
                ('eye_size', models.DecimalField(decimal_places=2, max_digits=25)),
                ('experience', models.IntegerField(help_text='Experience Points')),
                ('mouth_status', models.CharField(blank=True, choices=[('h', 'Happy'), ('n', 'Nervous'), ('d', 'displeased'), ('hu', 'Hungry')], default='h', help_text='Type of Nugget Mouth', max_length=1)),
                ('eye_status', models.CharField(blank=True, choices=[('w', 'Wide'), ('s', 'Small'), ('sl', 'Sleepy'), ('m', 'Mad')], default='w', help_text='Type of Nugget Eye', max_length=1)),
                ('nugget_status', models.CharField(blank=True, choices=[('e', 'Egg-like'), ('r', 'Round'), ('t', 'Triangle'), ('s', 'Square')], default='e', help_text='Type of Nugget Shape', max_length=1)),
                ('nug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.User')),
            ],
            options={
                'ordering': ['nug_id', 'mouth_status', 'eye_status', 'nugget_status', 'experience'],
            },
        ),
    ]
