# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0004_nuggetattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField(help_text='Unique Item ID')),
                ('Item_name', models.CharField(help_text='Name of Item(s)', max_length=50)),
                ('Inv_id', models.IntegerField(help_text='Unique Inventory ID')),
            ],
            options={
                'ordering': ['Item_id', 'Item_name', 'Inv_id'],
            },
        ),
    ]
