# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0005_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Inventorie',
        ),
        migrations.RenameModel(
            old_name='NuggetAttributes',
            new_name='NuggetAttribute',
        ),
    ]
