# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0006_auto_20171022_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(help_text='Unique Item ID')),
                ('item_name', models.CharField(help_text='Name of item', max_length=25)),
                ('item_status', models.CharField(blank=True, choices=[('a', 'Armor'), ('c', 'Consumables')], default='c', help_text='Type of Item', max_length=1)),
            ],
            options={
                'ordering': ['item_id', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Item')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventorie',
            options={'ordering': ['item_id', 'inv_id']},
        ),
        migrations.RenameField(
            model_name='inventorie',
            old_name='Inv_id',
            new_name='inv_id',
        ),
        migrations.RemoveField(
            model_name='inventorie',
            name='Item_id',
        ),
        migrations.RemoveField(
            model_name='inventorie',
            name='Item_name',
        ),
        migrations.AddField(
            model_name='nugget',
            name='atributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.NuggetAttribute'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Inventorie'),
        ),
        migrations.AddField(
            model_name='inventorie',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Item'),
        ),
    ]
