# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0008_auto_20171024_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.IntegerField(db_column='friends')),
                ('added', models.IntegerField(db_column='added_friends')),
                ('pending', models.IntegerField(db_column='pending_friends')),
                ('nug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Nugget')),
            ],
            options={
                'ordering': ['nug_id'],
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='nug_xp',
            field=models.IntegerField(default='0', help_text='Nugget Experience'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_features',
            field=models.CharField(blank=True, choices=[('he', 'Health'), ('hun', 'Hunger'), ('def', 'Defense'), ('f', 'Fatigue'), ('i', 'Intelligence'), ('happ', 'Happiness'), ('l', 'luck')], default='he', help_text='Type of Feature', max_length=1),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='battle_xp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.battle'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='defense',
            field=models.IntegerField(default='0', help_text='Nugget Defense'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='fatigue',
            field=models.IntegerField(default='0', help_text='Nugget Fatigue'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='happiness',
            field=models.IntegerField(default='0', help_text='Nugget Happiness'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='hunger',
            field=models.IntegerField(default='0', help_text='Nugget Hunger'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='intelligence',
            field=models.IntegerField(default='0', help_text='Nugget Intelligence'),
        ),
        migrations.AddField(
            model_name='nuggetattribute',
            name='luck',
            field=models.IntegerField(default='0', help_text='Nugget Luck'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='experience',
            field=models.IntegerField(default='0', help_text='Experience Points'),
        ),
    ]
