# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0010_auto_20171029_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='opponent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Nug_IDs'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='battle_xp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Battle'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='nug_size',
            field=models.IntegerField(default=20, help_text='Nugget size'),
        ),
    ]
