# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0011_auto_20171029_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='opponent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Nug_IDs'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_features',
            field=models.CharField(blank=True, choices=[('he', 'Health'), ('hun', 'Hunger'), ('def', 'Defense'), ('f', 'Fatigue'), ('i', 'Intelligence'), ('happ', 'Happiness'), ('l', 'luck')], default='he', help_text='Type of Feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(blank=True, choices=[('a', 'Armor'), ('c', 'Consumables')], default='c', help_text='Type of Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='battle_xp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Battle'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='eye_size',
            field=models.IntegerField(default=10, help_text='Eye size'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='mouth_size',
            field=models.IntegerField(default=10, help_text='Mouth size'),
        ),
    ]
