# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0013_auto_20171029_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='opponent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Nug_IDs'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='battle_XP',
            field=models.IntegerField(default=100, help_text='Battle Experience Points'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='defense',
            field=models.IntegerField(default=100, help_text='Nugget Defense'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='experience',
            field=models.IntegerField(default=50, help_text='Experience Points'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='fatigue',
            field=models.IntegerField(default=100, help_text='Nugget Fatigue'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='happiness',
            field=models.IntegerField(default=100, help_text='Nugget Happiness'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='hunger',
            field=models.IntegerField(default=100, help_text='Nugget Hunger'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='intelligence',
            field=models.IntegerField(default=20, help_text='Nugget Intelligence'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='luck',
            field=models.IntegerField(default=20, help_text='Nugget Luck'),
        ),
        migrations.AlterField(
            model_name='nuggetattribute',
            name='nug_health',
            field=models.IntegerField(default=100, help_text='health of nugget'),
        ),
    ]
