# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nugget', '0014_auto_20171029_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nugget.Nug_IDs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nug_id',
            field=models.IntegerField(help_text='Nugget ID unique to User', primary_key=True, serialize=False),
        ),
    ]
